### ISSUE TITLE
add mode

### ISSUE THREAD

**Issue by Loric0** [galyfray/SimplyCity#1]
pour rajouté des mode

SCP lockdows mais il faudrais enlever le spawn des mob + pour la décoration :D 

MrCrayfishs pour des voiture

RFTool pour le stockage + les ancenseur

Sécuriticraft pour la sécurité

draconic evolution

**Comment by galyfray** [comment]
SCP et vraiment un mod classe mais je ne pense pas l'ajouter a ce modpack car il ne me parait pas rentrer dans l'idée mais je le garde sous le coude pour un autre mod pack il est vraiment dans la veine de ce que je cherchais pour le prochain.

MrCrayfish's Vehicle Mod n'est pas stable et même si il a l'air sympa je préfère pas.

RFTool : nan j'e veut pas dans ce pack il y as déja ce qu'il faut pour le stockage 

Security Craft : oui bah ouais pourquoi pas je pense dans la pre-04 mais oui 

draconic evolution : non lui aussi je n'en veux pas dans ce pack il rentre pas dans mon idée du pack 

je compte rajouter Ztones simply jetpack et flux networks dans la pre-04 le modpack et prévus pour être petit donc je limite le nombre de mod
